services:
  database:
    image: postgres:16
    container_name: database 
    environment:
      POSTGRES_DB: ReservaSpace 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      PORT: 3333
      DB_DIALECT: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ReservaSpace 
      JWT_SECRET: 123
    volumes:
      - .:/api
      - /api/node_modules
    command: npm run dev
    depends_on:
      - database 

volumes:
  pgdata:
